/** Mayor Beauty Place booking catalog (shared by the runtime bootstrap and the seed script). */
export const CATALOG: Array<{ category: string; services: string[] }> = [
  {
    category: "Massage Treatment",
    services: [
      "G5 Massage",
      "Back and Shoulders Massage",
      "Indian Head Massage",
      "Face Massage",
      "Full Leg Massage",
      "Full Body Swedish Massage",
      "Hot Stone Massage",
      "Lymphatic Drainage Massage (1 Session)",
      "Lymphatic Drainage Massage (For 3–10 Sessions) – Price Per Session",
    ],
  },
  { category: "Teeth Whitening", services: ["LED Light Teeth Whitening"] },
  {
    category: "Body Sculpting",
    services: [
      "Wood Therapy",
      "Cryolipolysis or Fat Freezing (1 Area)",
      "Cryolipolysis or Fat Freezing (2 Areas)",
      "Cryolipolysis or Fat Freezing (3 Areas)",
    ],
  },
  {
    category: "Ultrasonic Cavitation",
    services: ["1 Area", "2 Areas", "3 Areas", "Herbal Vaginal Steam"],
  },
  {
    category: "Booty Facial Treatments",
    services: ["Booty Facial Treatment (For Women Only)"],
  },
  {
    category: "Photoshoot Section",
    services: [
      "Professional Makeup + Photoshoot (Single Outfit)",
      "Single Outfit Picture Only",
      "Family Shoot (Including One Person Makeup)",
    ],
  },
  {
    category: "Manicure Treatments",
    services: [
      "Full Set BIAB French Tip",
      "Infill BIAB French Tip",
      "Spa Manicure",
      "Luxury Spa Manicure With Paraffin Wax",
      "Nail Polish Only",
      "Full Set BIAB One Colour",
      "Marble Nail Art",
      "Gel Polish Only",
      "Ombre",
      "Normal Polish Only",
      "Full Set Normal Polish",
      "Full Set Gel Polish",
      "Infill Normal Polish",
      "Infill Gel Polish",
      "Full Set French Tip",
      "Spa Manicure Normal Polish",
      "Luxury Spa Manicure With Gel Polish",
      "Gel Polish With French Tip Design (No Acrylic)",
      "Acrylic Overlay on Toe With One Colour Gel Polish",
      "Acrylic Overlay on Toe With French Tip Polish",
      "Men's Manicure",
      "Acrylic Take Off",
      "Gel Polish Take Off",
      "Full Set Acrylic (One Colour Gel Polish)",
      "Infill Acrylic (One Colour Gel Polish)",
      "Full Set Acrylic French Tip",
      "Infill Acrylic French Tip",
      "Chrome Nails Full Set (One Colour) Acrylic",
      "Chrome Full Set One Colour on BIAB",
      "Chrome Full Set French Tip",
      "Cat Eye (One Colour) Acrylic",
      "Cat Eye French Tip Acrylic",
      "BIAB Full Set (One Colour) Chrome",
      "BIAB French Tip Chrome",
      "One Colour Chrome on Natural Nails",
      "French Tip Chrome on Natural Nail",
      "Cat Eye One Colour on Natural Nail",
      "Cat Eye French Tip on Natural Nail",
    ],
  },
  {
    category: "Pedicure",
    services: [
      "Spa Pedicure",
      "Luxury Spa Pedicure With Steam and One Colour Gel Polish",
      "Shellac Polish Only",
      "Full Set Acrylic One Colour",
      "Full Set Acrylic French Tip",
      "Acrylic on Two Big Toes With One Colour Gel Polish",
      "Acrylic on Two Big Toes With French Tip Polish",
      "One Colour Gel Polish on Natural Toe Nails",
      "French Tip on Natural Toe Nails",
      "Gel Take Off on Toes",
      "Acrylic Take Off From Toes",
      "Men's Pedicure",
      "Pedicure With Normal Polish",
      "Pedicure With One Colour Gel Polish",
      "Pedicure With French Tip Gel Polish",
      "Pedicure With Gel Take Off and One Colour Gel Polish",
      "Pedicure With Gel Take Off and French Tip Gel Polish",
      "Pedicure With Full Set Acrylic One Colour",
      "Pedicure With Full Set Acrylic French Tip",
      "Chrome Nails Full Set (One Colour) Acrylic",
      "Chrome Full Set One Colour on BIAB",
      "Chrome Full Set French Tip",
      "Cat Eye (One Colour) Acrylic",
      "Cat Eye French Tip Full Set Acrylic",
      "BIAB Full Set (One Colour) Chrome",
      "BIAB Full Set French Tip Chrome",
      "One Colour Chrome on Natural Nails",
      "French Tip Chrome on Natural Nail",
      "Cat Eye One Colour on Natural Nail",
      "Cat Eye French Tip on Natural Nail",
      "One Colour Chrome on Natural Nails With Two Big Toe Acrylic",
      "French Tip Chrome on Natural Nail With Two Big Toe Acrylic/BIAB",
      "Cat Eye One Colour on Natural Nail With Two Big Toe Acrylic/BIAB",
      "Cat Eye French Tip on Natural Nail With Two Big Toe Acrylic/BIAB",
    ],
  },
  {
    category: "Facial Treatments",
    services: [
      "Mini Facial",
      "Herbal Facial",
      "Luxury Facial With Extraction",
      "Anti-Ageing Luxury Facial",
      "Electro Facial",
    ],
  },
  {
    category: "Body Treatment",
    services: [
      "Full Body Scrub With Sauna",
      "Herbal Body Polish With Sauna",
      "Back Cleaning Treatment",
    ],
  },
  {
    category: "Permanent Makeup",
    services: ["Microblading Brows", "Microshading Brows", "Combo Brows", "Top Up"],
  },
  {
    category: "Waxing Hair Removal",
    services: [
      "Hollywood Waxing",
      "Brazilian Hot Wax",
      "Bikini Line",
      "Half Leg",
      "Full Leg",
      "Under Arm Waxing",
      "Full Hand Waxing",
      "Upper Lip",
      "Stomach Waxing",
      "Face Waxing (Without Forehead)",
      "Full Body Waxing (Including Bikini Line)",
      "Back Waxing",
    ],
  },
  {
    category: "Make Up",
    services: [
      "Evening Makeup",
      "Day Makeup",
      "Baby Dedication Makeup",
      "Birthday Glam Makeup",
      "Bridal Makeup",
      "Gele / Head Tie",
    ],
  },
  {
    category: "Eyelash",
    services: [
      "Classic",
      "Hybrid Lash",
      "Russian Volume Lash",
      "Classic Infill",
      "Hybrid Infill",
      "Russian Volume Infill",
      "Lash Remover",
      "Brow Lamination",
      "Lash Lift",
      "Brow Lamination, Tint and Shaping",
      "Wispy Volume Lashes",
      "Mega Volume Lashes",
      "Bottom Lash",
      "Mega Volume Infill",
      "Cluster Lashes (Normal)",
      "Cluster Lashes (Extra Full)",
      "Lash Lift & Tint",
    ],
  },
  {
    category: "Eyebrow",
    services: [
      "Eyebrow Threading / Wax",
      "Tinting",
      "Eyebrow Threading + Tinting",
      "Eyebrow + Upper Lips",
      "Eyebrow + Upper Lips + Chin",
      "Chin",
      "Side",
      "Forehead",
    ],
  },
];
